# Generated by Django 5.2.14 on 2026-06-02 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_role_userprofile_userinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='day_of_exrsice',
            field=models.IntegerField(blank=True, help_text='days of your exrsice in weak', null=True),
        ),
    ]
