# Generated by Django 5.2.14 on 2026-06-17 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_userinfo_day_of_exrsice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='tall',
            new_name='hight',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='day_of_exrsice',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='goal',
            field=models.CharField(blank=True, choices=[('BULK', 'BULK'), ('', 'CUT'), ('Stay same', 'Stay same')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='activety',
            field=models.CharField(choices=[('1.2', 'No Exersice'), ('1.37', 'Exersice 1-3 days/week '), ('1.55', 'Exersice 3-5 days/week '), ('1.72', 'Exersice 6-7 days/week'), ('1.9', 'Profishinal')], default='1.37', max_length=70),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=50),
        ),
    ]
