# Generated by Django 5.2.14 on 2026-06-18 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_tall_userprofile_hight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='activety',
            field=models.CharField(choices=[('1.2', 'No Exersice'), ('1.37', 'Exersice 1-3 days/week '), ('1.55', 'Exersice 3-5 days/week '), ('1.72', 'Exersice 6-7 days/week'), ('1.9', 'Profishinal')], max_length=70),
        ),
    ]
