# Generated by Django 5.2.14 on 2026-06-18 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_userprofile_hight_alter_userprofile_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='hight',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
