# Generated by Django 5.2.14 on 2026-06-24 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_userprofile_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Admin', 'Admin'), ('Coach', 'Coach'), ('Trainee', 'Trainee')], default='Trainee', max_length=10),
        ),
    ]
