# Generated by Django 5.2.14 on 2026-06-04 12:29

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mucsle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Split',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('pro split', 'Pro Split'), ('Arnold_split', 'Arnold_split'), ('Push Pull Leg', 'Push Pull Leg'), ('Upper Lower', 'Upper Lower')], default='pro split', max_length=50)),
                ('description', models.TextField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_workout_day', models.CharField(choices=[('Back', 'Back'), ('Bench', 'Bench'), ('Shoulders', 'Shoulders'), ('Arms', 'Arms'), ('Legs', 'Legs'), ('Push', 'Push'), ('Pull', 'Pull'), ('Upper', 'Upper'), ('Lower', 'Lower'), ('Full Body', 'Full Body'), ('Back & Bench', 'Back & Bench'), ('Shoulder & Arm', 'Shoulder & Arm')], default='Full Body', validators=[django.core.validators.MaxLengthValidator(50), django.core.validators.MinLengthValidator(3)])),
                ('level', models.CharField(choices=[('Begainer', 'Begainer'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='Begainer')),
                ('split_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='split', to='workouts.split')),
            ],
        ),
    ]
