# Generated by Django 5.2.14 on 2026-06-04 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mucsle',
            name='description',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mucsle',
            name='name_muscle',
            field=models.CharField(choices=[('Lat Pull Down', 'Lat Pull Down'), ('Pull Ups', 'Pull Ups'), ('Chin Ups', 'Chin Ups'), ('One Arm Dumbbell Row', 'One Arm Dumbbell Row'), ('T Bar Row', 'T Bar Row'), ('Wide T Bar Row', 'Wide T Bar Row'), ('Seated Cable Row', 'Seated Cable Row'), ('Reverse Fly', 'Reverse Fly'), ('Barbell Row', 'Barbell Row'), ('Wide Barbell Row', 'Wide Barbell Row'), ('Row', 'Row'), ('Wide Row', 'Wide Row'), ('Back Extension', 'Back Extension'), ('Pull Down Stretch', 'Pull Down Stretch'), ('Bench Press', 'Bench Press'), ('Incline Press', 'Incline Press'), ('Dumbbell Press', 'Dumbbell Press'), ('Incline Dumbbell Press', 'Incline Dumbbell Press'), ('Dumbbell Fly', 'Dumbbell Fly'), ('Flies', 'Flies'), ('Bench Cable Pushdown', 'Bench Cable Pushdown'), ('Incline Bench Press', 'Incline Bench Press'), ('Push Ups', 'Push Ups'), ('Wide Push Ups', 'Wide Push Ups'), ('Diamond Push Ups', 'Diamond Push Ups'), ('Cable Flies', 'Cable Flies'), ('Dips', 'Dips'), ('Shoulder Press', 'Shoulder Press'), ('Dumbbell Shoulder Press', 'Dumbbell Shoulder Press'), ('Lateral Raises', 'Lateral Raises'), ('Front Raises', 'Front Raises'), ('Cable Lateral Raises', 'Cable Lateral Raises'), ('Cable Row Front Raises', 'Cable Row Front Raises'), ('Upright Row', 'Upright Row'), ('Face Pulls', 'Face Pulls'), ('Bent Over Lateral Raise', 'Bent Over Lateral Raise'), ('Shoulder Reverse Dumbbell', 'Shoulder Reverse Dumbbell'), ('Cable Shrugs', 'Cable Shrugs'), ('Dumbbell Shrugs', 'Dumbbell Shrugs'), ('Bar Shrugs', 'Bar Shrugs'), ('Cable Biceps Curl', 'Cable Biceps Curl'), ('Barbell Biceps Curl', 'Barbell Biceps Curl'), ('Dumbbell Biceps Curl', 'Dumbbell Biceps Curl'), ('Hammer Biceps Curl', 'Hammer Biceps Curl'), ('Cable Rope Hammer', 'Cable Rope Hammer'), ('Concentration Curl', 'Concentration Curl'), ('Cable Bar Curl', 'Cable Bar Curl'), ('Preacher Curl', 'Preacher Curl'), ('Close Grip Bench Press', 'Close Grip Bench Press'), ('Overhead Triceps', 'Overhead Triceps'), ('Kick Back', 'Kick Back'), ('Cable Rope Pushdown', 'Cable Rope Pushdown'), ('V Bar Pushdown', 'V Bar Pushdown'), ('Cable Overhead', 'Cable Overhead'), ('Grip Pushdown', 'Grip Pushdown'), ('Reverse Grip Pushdown', 'Reverse Grip Pushdown'), ('Squat', 'Squat'), ('Leg Extension', 'Leg Extension'), ('Leg Curl', 'Leg Curl'), ('Leg Press', 'Leg Press'), ('Romanian Deadlift', 'Romanian Deadlift'), ('Glute Ham Raise', 'Glute Ham Raise'), ('Standing Calf Raise', 'Standing Calf Raise'), ('Seated Calf Raise', 'Seated Calf Raise'), ('Adductor Machine', 'Adductor Machine'), ('Abductor Machine', 'Abductor Machine'), ('Forward Lunge', 'Forward Lunge'), ('Walking Lunge', 'Walking Lunge'), ('Barbell Lunge', 'Barbell Lunge'), ('Bulgarian Split Squat', 'Bulgarian Split Squat'), ('Hack Squat', 'Hack Squat'), ('Smith Machine Squat', 'Smith Machine Squat'), ('Goblet Squat', 'Goblet Squat'), ('Sumo Squat', 'Sumo Squat'), ('Deadlift', 'Deadlift'), ('Hip Thrust', 'Hip Thrust')], default='Push Ups', max_length=30),
        ),
        migrations.CreateModel(
            name='RoutineExrsice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sets', models.PositiveIntegerField(default=3)),
                ('reps', models.PositiveIntegerField(default=10)),
                ('exrsice', models.ManyToManyField(to='workouts.mucsle')),
                ('routine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routine', to='workouts.workout')),
            ],
        ),
    ]
