# Generated by Django 5.2.14 on 2026-06-04 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_mucsle_description_mucsle_name_muscle_routineexrsice'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mucsle',
            new_name='MuscleExrsice',
        ),
    ]
