# Generated by Django 5.2.14 on 2026-06-06 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0003_rename_mucsle_muscleexrsice'),
    ]

    operations = [
        migrations.AddField(
            model_name='split',
            name='level',
            field=models.CharField(choices=[('Begainer', 'Begainer'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='Begainer'),
        ),
    ]
