# Generated by Django 5.2.14 on 2026-06-06 14:38

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0004_split_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exrsice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_muscle', models.CharField(validators=[django.core.validators.MaxLengthValidator(60), django.core.validators.MinLengthValidator(3)])),
                ('group_muscle', models.CharField(choices=[('Chest', 'Chest'), ('Back', 'Back'), ('Shoulders', 'Shoulders'), ('Biceps', 'Biceps'), ('Triceps', 'Triceps'), ('Legs', 'Legs'), ('Abs', 'Abs')])),
                ('description', models.TextField(blank=True, null=True)),
                ('video_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='routineexrsice',
            name='exrsice',
        ),
        migrations.RemoveField(
            model_name='routineexrsice',
            name='routine',
        ),
        migrations.RemoveField(
            model_name='workout',
            name='split_system',
        ),
        migrations.RemoveField(
            model_name='split',
            name='name',
        ),
        migrations.AddField(
            model_name='split',
            name='system',
            field=models.CharField(choices=[('Pro split', 'pro split'), ('Push Pull Leg', 'Push Pull Leg'), ('Arnold', 'Arnold'), ('Intirior & Extirior', 'Intirior & Extirior'), ('Upper & Lower', 'Upper & Lower'), ('Full Body', 'Full Body')], default='Pro split'),
        ),
        migrations.AlterField(
            model_name='split',
            name='level',
            field=models.CharField(choices=[('Brgainer', 'Brgainer'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='Brgainer'),
        ),
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reps', models.PositiveIntegerField()),
                ('sets', models.PositiveIntegerField()),
                ('exrsice', models.ManyToManyField(related_name='exrsice', to='workouts.exrsice')),
                ('split', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='split', to='workouts.split')),
            ],
        ),
        migrations.DeleteModel(
            name='MuscleExrsice',
        ),
        migrations.DeleteModel(
            name='RoutineExrsice',
        ),
        migrations.DeleteModel(
            name='WorkOut',
        ),
    ]
