# Generated by Django 5.2.14 on 2026-06-06 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0005_exrsice_remove_routineexrsice_exrsice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='split',
            name='system',
            field=models.CharField(choices=[('Pro split', 'pro split'), ('Push Pull Leg', 'Push Pull Leg'), ('Arnold', 'Arnold'), ('Intirior & Extirior', 'Intirior & Extirior'), ('Upper & Lower', 'Upper & Lower'), ('Full Body', 'Full Body')]),
        ),
    ]
