# Generated by Django 5.2.14 on 2026-06-06 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0006_alter_split_system'),
    ]

    operations = [
        migrations.AlterField(
            model_name='split',
            name='level',
            field=models.CharField(choices=[('Brgainer', 'Brgainer'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')]),
        ),
    ]
