# Generated by Django 5.2.14 on 2026-06-07 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0007_alter_split_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProgramDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SecondryMuscle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='routine',
            name='exrsice',
        ),
        migrations.RemoveField(
            model_name='routine',
            name='split',
        ),
        migrations.RemoveField(
            model_name='split',
            name='level',
        ),
        migrations.RemoveField(
            model_name='split',
            name='system',
        ),
        migrations.AddField(
            model_name='split',
            name='split_type',
            field=models.CharField(choices=[('Push Pull Leg', 'Push Pull Leg'), ('Pro Split', 'Pro Split'), ('Arnold Split', 'Arnold Split'), ('Upper & Lower', 'Upper & Lower'), ('Intirior & Extirior', 'Intirior Extirior'), ('Full Body', 'Full Body')], default='Pro Split', max_length=50),
        ),
        migrations.CreateModel(
            name='Exersice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('primary_muscle', models.CharField(choices=[('CHEST', 'Chest'), ('BACK', 'Back'), ('SHOULDERS', 'Shoulders'), ('BICEPS', 'Biceps'), ('TRICEPS', 'Triceps'), ('LEGS', 'Legs'), ('ABS', 'Abs'), ('CALVES', 'Calves')])),
                ('difcullty', models.CharField(choices=[('beginner', 'Breinner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('profisional', 'Profisional')])),
                ('video', models.URLField()),
                ('equipment', models.ManyToManyField(related_name='equipments', to='workouts.equipment')),
                ('secondry_muscle', models.ManyToManyField(related_name='secondry_muscles', to='workouts.secondrymuscle')),
            ],
        ),
        migrations.CreateModel(
            name='ProgramExersice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('sets', models.PositiveIntegerField()),
                ('min_reps', models.PositiveIntegerField()),
                ('max_reps', models.PositiveIntegerField()),
                ('rest_minutes', models.PositiveIntegerField()),
                ('exersice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_exersices', to='workouts.exersice')),
                ('program_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exersices', to='workouts.programday')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('program_day', 'order')},
            },
        ),
        migrations.CreateModel(
            name='ProgramTemlate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ex: Pro split Begainer,....', max_length=50)),
                ('level', models.CharField(choices=[('beginner', 'Breinner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('profisional', 'Profisional')])),
                ('description', models.TextField(blank=True, max_length=200, null=True)),
                ('split', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='splits', to='workouts.split')),
            ],
        ),
        migrations.AddField(
            model_name='programday',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workouts.programtemlate'),
        ),
        migrations.DeleteModel(
            name='Exrsice',
        ),
        migrations.DeleteModel(
            name='Routine',
        ),
        migrations.AlterUniqueTogether(
            name='programday',
            unique_together={('program', 'order')},
        ),
    ]
