# Generated by Django 5.2.14 on 2026-06-07 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0008_equipment_programday_secondrymuscle_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='split',
            name='split_type',
            field=models.CharField(choices=[('Push Pull Leg', 'Push Pull Leg'), ('Pro Split', 'Pro Split'), ('Arnold Split', 'Arnold Split'), ('Upper & Lower', 'Upper & Lower'), ('Intirior & Extirior', 'Intirior Extirior'), ('Full Body', 'Full Body')], max_length=50),
        ),
    ]
