# Generated by Django 5.2.14 on 2026-06-07 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0009_alter_split_split_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='split',
            name='description',
            field=models.TextField(blank=True, max_length=400, null=True),
        ),
    ]
