# Generated by Django 5.2.14 on 2026-06-07 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0010_alter_split_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programexersice',
            name='exersice',
        ),
        migrations.AddField(
            model_name='programexersice',
            name='exersice',
            field=models.ManyToManyField(related_name='program_exersices', to='workouts.exersice'),
        ),
    ]
