# Generated by Django 5.2.14 on 2026-06-07 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0011_remove_programexersice_exersice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exersice',
            name='video',
            field=models.URLField(blank=True, null=True),
        ),
    ]
