# Generated by Django 5.2.14 on 2026-06-07 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0012_alter_exersice_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exersice',
            name='equipment',
            field=models.ManyToManyField(blank=True, null=True, related_name='equipments', to='workouts.equipment'),
        ),
        migrations.AlterField(
            model_name='exersice',
            name='secondry_muscle',
            field=models.ManyToManyField(blank=True, null=True, related_name='secondry_muscles', to='workouts.secondrymuscle'),
        ),
    ]
