# Generated by Django 5.2.14 on 2026-06-08 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0013_alter_exersice_equipment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='programexersice',
            name='slug',
            field=models.SlugField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='exersice',
            name='difcullty',
            field=models.CharField(blank=True, choices=[('beginner', 'Breinner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('profisional', 'Profisional')], null=True),
        ),
    ]
